{{- if .Values.ingress.enabled -}}
apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: {{ include "weather.fullname" . }}
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: infrastructure@mito.ai
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: {{ include "weather.fullname" . }}-iss
    # Enable HTTP01 validations
    http01: {}
{{- end -}}